* SQL injection example
** Setup and sample run
   Execute the following in a bourne-style shell, one block at a time to see
   results. 

  #+BEGIN_SRC sh
    # Prepare db
    ./admin -r
    ./admin -c
    ./admin -s 

    # Add regular user
    ./add-user.py 2>> log
    First User

    # Check
    ./admin -s

    # Add Johnny Droptable 
    ./add-user.py 2>> log
    Johnny'); DROP TABLE users; --

    # See the problem:
    ./admin -s

    # Check the log
    tail log
  #+END_SRC

** Build codeql database
   #+BEGIN_SRC sh
     #* Build the db with source commit id.
     codeql --version
     : CodeQL command-line toolchain release 2.13.5.

     cd ~/local/codeql-dataflow-sql-injection-python

     DB=./python-sqli-db-$(git rev-parse --short HEAD)

     echo $DB
     test -d "$DB" && rm -fR "$DB"
     mkdir -p "$DB"

     codeql database create --language=python -s . -j 8 -v $DB

   #+END_SRC

** CodeQL setup
   These examples are written against v2.13.5 of the cli.  To set up the packages,
   use
   #+BEGIN_SRC sh
     codeql pack install
   #+END_SRC

** Reading Order
   The queries introduce CodeQL concepts and should be read bottom-up in this
   order:
   1. =source.ql=: introduces Value, ControlFlowNode and DataFlow::Node
   2. =sink.ql=: introduces AstNode
   3. =TaintFlowTemplate.ql=: introduce the taint flow template
   4. =TaintFlow.ql=: taint flow with endpoints only
   5. =TaintFlowPath.ql=: taint flow with full path

** Note on the Python code
   The Python call 
   : conn.execute(query)
   to sqlite3 only allows one statement and produces an exception:
   : sqlite3.Warning: You can only execute one statement at a time.
   This makes it safer than the raw
   : sqlite3_exec() 
   or Python's
   : conn.executescript
   
   For this tutorial, we use the multi-statement =executescript()= call.
